<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class FnIncidentesPeriodo extends Migration
{
    public function up()
    {
        $sql = ""
            ."/* "
            ."Función incidentes_periodo(fech_ini, fech_fin, tolerancia_retardo, tolerancia_asistencia) "
            ."----------------------- "
            ."Obtiene incidentes por empleado entre dos fechas "
            ."*/ "
            ."create or replace function incidentes_periodo(fech_ini date, fech_fin date, tolerancia_retardo varchar, tolerancia_asistencia varchar) "
            ."returns table(id_empleado int, fecha date, hora_entrada time, hora_salida time, horario_entrada time, horario_salida time, cve_tipo_incidente text, cve_tipo_cobertura text) as "
            ."$$ "
            ."begin "
                ."return query "
                ."with incidentes_todos as ( "
                    ."/* incidentes de entrada, inasistencias y días sin incidentes */ "
                    ."select "
                        ."a.id_empleado, a.fecha, a.hora_entrada, a.hora_salida, h.hora_entrada as horario_entrada, h.hora_salida as horario_salida, "
                        ."(select "
                            ."case when a.hora_entrada is not null then "
                                ."/* día con asistencia */ "
                                ."case when a.hora_entrada <> a.hora_salida then "
                                    ."/* dos checadas */ "
                                    ."case when date_trunc('minute', a.hora_entrada) > h.hora_entrada + '0:15'::interval then "
                                        ."/* entrada después de hora de entrada + tolerancia */ "
                                        ."case when date_trunc('minute', a.hora_entrada) <= h.hora_entrada + '0:30'::interval then "
                                            ."/* entrada después de tolerancia pero dentro de retardo */ "
                                            ."'retardo' "
                                        ."else "
                                            ."/* entrada después de tolerancia y después de retardo */ "
                                            ."'entrada_tardia' "
                                        ."end "
                                    ."end "
                                ."else "
                                    ."/* solamente una checada */ "
                                    ."case when a.hora_entrada > '12:00' then "
                                        ."/* checada después de las 12 del día, se considera checada de salida */ "
                                        ."'sin_entrada' "
                                    ."else "
                                        ."/* checada antes de las 12 del día, se considera checada de entrada */ "
                                        ."case when date_trunc('minute', a.hora_entrada) > h.hora_entrada + '0:15'::interval then "
                                            ."/* entrada después de hora de entrada + tolerancia */ "
                                            ."case when date_trunc('minute', a.hora_entrada) <= h.hora_entrada + '0:30'::interval then "
                                                ."/* entrada después de tolerancia pero dentro de retardo */ "
                                                ."'retardo' "
                                            ."else "
                                                ."/* entrada después de tolerancia y después de retardo */ "
                                                ."'entrada_tardia' "
                                            ."end "
                                        ."end "
                                    ."end "
                                ."end "
                            ."else "
                                ."case when a.fecha < now() then "
                                    ."'inasistencia' "
                                ."end "
                            ."end "
                        .") as cve_tipo_incidente, "
                        ."(select "
                            ."case when a.hora_entrada is not null then "
                                ."/* día con asistencia */ "
                                ."case when a.hora_entrada <> a.hora_salida then "
                                    ."/* dos checadas */ "
                                    ."case when date_trunc('minute', a.hora_entrada) > h.hora_entrada + '0:15'::interval then "
                                        ."/* entrada después de hora de entrada + tolerancia */ "
                                        ."case when date_trunc('minute', a.hora_entrada) <= h.hora_entrada + '0:30'::interval then "
                                            ."/* entrada después de tolerancia pero dentro de retardo */ "
                                            ."'entrada' "
                                        ."else "
                                            ."/* entrada después de tolerancia y después de retardo */ "
                                            ."'entrada' "
                                        ."end "
                                    ."end "
                                ."else "
                                    ."/* solamente una checada */ "
                                    ."case when a.hora_entrada > '12:00' then "
                                        ."/* checada después de las 12 del día, se considera checada de salida */ "
                                        ."'entrada' "
                                    ."else "
                                        ."/* checada antes de las 12 del día, se considera checada de entrada */ "
                                        ."case when date_trunc('minute', a.hora_entrada) > h.hora_entrada + '0:15'::interval then "
                                            ."/* entrada después de hora de entrada + tolerancia */ "
                                            ."case when date_trunc('minute', a.hora_entrada) <= h.hora_entrada + '0:30'::interval then "
                                                ."/* entrada después de tolerancia pero dentro de retardo */ "
                                                ."'entrada' "
                                            ."else "
                                                ."/* entrada después de tolerancia y después de retardo */ "
                                                ."'entrada' "
                                            ."end "
                                        ."end "
                                    ."end "
                                ."end "
                            ."else "
                                ."case when a.fecha < now() then "
                                    ."'dia' "
                                ."end "
                            ."end "
                        .") as cve_tipo_cobertura "
                    ."from "
                        ."asistencias_periodo(fech_ini, fech_fin) a "
                        ."left join horarios_periodo(fech_ini, fech_fin) h on a.id_empleado = h.id_empleado and a.fecha = h.fecha "
                ."union "
                    ."/* incidentes de salida */ "
                    ."select "
                        ."a.id_empleado, a.fecha, a.hora_entrada, a.hora_salida, h.hora_entrada as horario_entrada, h.hora_salida as horario_salida, "
                        ."(select "
                            ."case when a.hora_entrada is not null then "
                                ."/* día con asistencia */ "
                                ."case when a.hora_entrada <> a.hora_salida then "
                                    ."/* dos checadas */ "
                                    ."case when a.hora_salida < h.hora_salida then "
                                        ."'salida_temprano' "
                                    ."end "
                                ."else "
                                    ."/* solamente una checada */ "
                                    ."case when a.hora_entrada > '12:00' then "
                                        ."/* checada después de las 12 del día, se considera checada de salida */ "
                                        ."case when a.hora_salida < h.hora_salida then "
                                            ."'salida_temprano' "
                                        ."end "
                                    ."else "
                                        ."/* checada antes de las 12 del día, se considera checada de entrada */ "
                                        ."'sin_salida' "
                                    ."end "
                                ."end "
                            ."end "
                        .") as cve_tipo_incidente, "
                        ."(select "
                            ."case when a.hora_entrada is not null then "
                                ."/* día con asistencia */ "
                                ."case when a.hora_entrada <> a.hora_salida then "
                                    ."/* dos checadas */ "
                                    ."case when a.hora_salida < h.hora_salida then "
                                        ."'salida' "
                                    ."end "
                                ."else "
                                    ."/* solamente una checada */ "
                                    ."case when a.hora_entrada > '12:00' then "
                                        ."/* checada después de las 12 del día, se considera checada de salida */ "
                                        ."case when a.hora_salida < h.hora_salida then "
                                            ."'salida' "
                                        ."end "
                                    ."else "
                                        ."/* checada antes de las 12 del día, se considera checada de entrada */ "
                                        ."'salida' "
                                    ."end "
                                ."end "
                            ."end "
                        .") as cve_tipo_cobertura "
                    ."from "
                        ."asistencias_periodo(fech_ini, fech_fin) a "
                        ."left join horarios_periodo(fech_ini, fech_fin) h on a.id_empleado = h.id_empleado and a.fecha = h.fecha "
                .") "
                    ."select "
                        ."* "
                    ."from "
                        ."incidentes_todos it "
                    ."where "
                        ."it.cve_tipo_cobertura is not null "
                ."union "
                    ."select "
                        ."ap.id_empleado, ap.fecha, ap.hora_entrada, ap.hora_salida, h.hora_entrada as horario_entrada, h.hora_salida as horario_salida, null as cve_tipo_incidente, null as cve_tipo_cobertura "
                    ."from "
                        ."asistencias_periodo(fech_ini, fech_fin) ap "
                        ."left join horarios_periodo(fech_ini, fech_fin) h on ap.id_empleado = h.id_empleado and ap.fecha = h.fecha "
                    ."where "
                        ."ap.fecha not in (select it2.fecha from incidentes_todos it2 where it2.id_empleado = ap.id_empleado and it2.cve_tipo_cobertura is not null) "
                ."order by "
                    ."fecha "
                ."; "
            ."end; "
            ."$$ language plpgsql strict immutable; "
            ."";
        $query = $this->db->query($sql);
    }

    public function down()
    {
        $sql = "drop function if exists incidentes_periodo(date, date, varchar, varchar) ";
        $query = $this->db->query($sql);
    }
}
