<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class FnIncidentesPeriodo extends Migration
{
    public function up()
    {
        $sql = ""
            ."/* "
            ."Función incidentes_periodo(fech_ini, fech_fin, tolerancia_retardo, tolerancia_asistencia) "
            ."----------------------- "
            ."Obtiene incidentes por empleado entre dos fechas "
            ."*/ "
            ."create or replace function incidentes_periodo(fech_ini date, fech_fin date, tolerancia_retardo varchar, tolerancia_asistencia varchar) "
            ."returns table(id_empleado int, fecha date, hora_entrada time, hora_salida time, id_incidente int) as "
            ."$$ "
            ."begin "
                ."return query "
            ." "
                ."/* incidentes de salida */ "
                ."with incidentes_salida as ( "
                    ."select "
                        ."a.id_empleado, a.fecha, a.hora_entrada, a.hora_salida, "
                        ."(select "
                            ."case when a.hora_entrada is not null then "
                                ."/* día con asistencia */ "
                                ."case when a.hora_entrada <> a.hora_salida then "
                                    ."/* dos checadas */ "
                                    ."case when a.hora_salida < h.hora_salida then "
                                        ."/* 'salida temprano' */ "
                                        ."5 "
                                    ."end "
                                ."else "
                                    ."/* solamente una checada */ "
                                    ."case when a.hora_entrada > '12:00' then "
                                        ."/* checada después de las 12 del día, se considera checada de salida */ "
                                        ."case when a.hora_salida < h.hora_salida then "
                                            ."/* 'salida temprano' */ "
                                            ."5 "
                                        ."end "
                                    ."else "
                                        ."/* checada antes de las 12 del día, se considera checada de entrada */ "
                                        ."/* 'sin salida' */ "
                                        ."10 "
                                    ."end "
                                ."end "
                            ."end "
                        .") as id_incidente "
                    ."from "
                        ."asistencias_periodo(fech_ini, fech_fin) a "
                        ."left join horarios_periodo(fech_ini, fech_fin) h on a.id_empleado = h.id_empleado and a.fecha = h.fecha "
                .") "
                    ."select * from incidentes_salida ins where ins.id_incidente is not null "
            ." "
                ."union "
            ." "
                ."/* incidentes de entrada, inasistencias y días sin incidentes */ "
                ."select "
                    ."a.id_empleado, a.fecha, a.hora_entrada, a.hora_salida, "
                    ."(select "
                        ."case when a.hora_entrada is not null then "
                            ."/* día con asistencia */ "
                            ."case when a.hora_entrada <> a.hora_salida then "
                                ."/* dos checadas */ "
                                ."case when date_trunc('minute', a.hora_entrada) > h.hora_entrada + '0:15'::interval then "
                                    ."/* entrada después de hora de entrada + tolerancia */ "
                                    ."case when date_trunc('minute', a.hora_entrada) <= h.hora_entrada + '0:30'::interval then "
                                        ."/* entrada después de tolerancia pero dentro de retardo */ "
                                        ."/* 'retardo' */ "
                                        ."2 "
                                    ."else "
                                        ."/* entrada después de tolerancia y después de retardo */ "
                                        ."/* 'entrada tardía' */ "
                                        ."4 "
                                    ."end "
                                ."end "
                            ."else "
                                ."/* solamente una checada */ "
                                ."case when a.hora_entrada > '12:00' then "
                                    ."/* checada después de las 12 del día, se considera checada de salida */ "
                                    ."/* 'sin entrada' */ "
                                    ."7 "
                                ."else "
                                    ."/* checada antes de las 12 del día, se considera checada de entrada */ "
                                    ."case when date_trunc('minute', a.hora_entrada) > h.hora_entrada + '0:15'::interval then "
                                        ."/* entrada después de hora de entrada + tolerancia */ "
                                        ."case when date_trunc('minute', a.hora_entrada) <= h.hora_entrada + '0:30'::interval then "
                                            ."/* entrada después de tolerancia pero dentro de retardo */ "
                                            ."/* 'retardo' */ "
                                            ."2 "
                                        ."else "
                                            ."/* entrada después de tolerancia y después de retardo */ "
                                            ."/* 'entrada tardía' */ "
                                            ."4 "
                                        ."end "
                                    ."end "
                                ."end "
                            ."end "
                        ."else "
                            ."case when a.fecha < now() then "
                                ."/* 'inasistencia' */ "
                                ."11 "
                            ."end "
                        ."end "
                    .") as id_incidente "
                ."from "
                    ."asistencias_periodo(fech_ini, fech_fin) a "
                    ."left join empleado e on a.id_empleado = e.id_empleado "
                    ."left join horarios_periodo(fech_ini, fech_fin) h on a.id_empleado = h.id_empleado and a.fecha = h.fecha "
                ."order by "
                    ."fecha "
                ."; "
            ."end; "
            ."$$ language plpgsql strict immutable; "
            ."";
        $query = $this->db->query($sql);
    }

    public function down()
    {
        $sql = "drop function if exists incidentes_periodo(date, date, varchar, varchar) ";
        $query = $this->db->query($sql);
    }
}
