<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class FnJustificacionPeriodo extends Migration
{
    public function up()
    {
        $sql = ""
            ."/* "
            ."Función justificacion_periodo(fech_ini, fech_fin, tolerancia_retardo, tolerancia_asistencia) "
            ."----------------------- "
            ."Obtiene justificacion de incidentes por empleado entre dos fechas "
            ."*/ "
            ."create or replace function justificacion_periodo(fech_ini date, fech_fin date, tolerancia_retardo varchar, tolerancia_asistencia varchar) "
            ."returns table(id_empleado int, fecha date, hora_entrada time, hora_salida time, horario_entrada time, horario_salida time, cve_tipo_incidente text, cve_tipo_cobertura text, tipo_justificante text, id_justificante int) as "
            ."$$ "
            ."begin "
                ."return query "
                ."/* "
                ."tipo_justificante "
                ."----------------- "
                ."1   día inhábil "
                ."2   justificante masivo tipo Día o Vacación sin especificar empleados a aplicar (aplica a todos) "
                ."3   justificante masivo tipo Día o Vacación especificando empleados a aplicar "
                ."4   justificante individual tipo Día o Vacación "
                ."5   justificante masivo tipo Entrada o Salida sin especificar empleados a aplicar (aplica a todos) "
                ."6   justificante masivo tipo Entrada o salida especificando empleados a aplicar "
                ."7   justificante individual tipo Entrada o Salida "
                ."8   cumple horas de trabajo "
            ." "
                ."incidentes de entrada "
                ."--------------------- "
                ."2   retardo "
                ."4   entrada tardía "
                ."7   sin entrada "
            ." "
                ."incidentes de salida "
                ."-------------------- "
                ."5   salida temprano "
                ."10  sin salida "
                ."*/ "
                ."select "
                    ."i.* "
                    .", (select valor from "
                        ."( "
                            ."select 1 as orden, 'di' as valor where di.id_dia_inhabil is not null "
                            ."union "
                            ."select 2 as orden, 'jm' as valor where jm.id_justificante_masivo is not null and jm.tipo_cobertura in ('dia','vacaciones') "
                            ."union "
                            ."select 3 as orden, 'jm' as valor where jm2.id_justificante_masivo is not null and jm2.tipo_cobertura in ('dia','vacaciones') "
                            ."union "
                            ."select 4 as orden, 'ji' as valor where j.id_justificante is not null and j.tipo_cobertura in ('dia','vacaciones') "
                            ."union "
                            ."select 5 as orden, 'jm' as valor where jm.id_justificante_masivo is not null and jm.tipo_cobertura not in ('dia','vacaciones') "
                            ."union "
                            ."select 6 as orden, 'jm' as valor where jm2.id_justificante_masivo is not null and jm2.tipo_cobertura not in ('dia','vacaciones') "
                            ."union "
                            ."select 7 as orden, 'ji' as valor where j.id_justificante is not null "
                            ."union "
                            ."select 8 as orden, 'hc' as valor where i.cve_tipo_incidente is not null and di.id_dia_inhabil is null and jm.id_justificante_masivo is null and j.id_justificante is null and date_trunc('minute', i.hora_salida) - date_trunc('minute', i.hora_entrada) >= '8:00' "
                            ."order by orden "
                        .") as tj "
                    ."limit 1 ) as tipo_justificante "
                    .", (select valor from "
                        ."( "
                            ."select 1 as orden, di.id_dia_inhabil as valor where di.id_dia_inhabil is not null "
                            ."union "
                            ."select 2 as orden, jm.id_justificante_masivo as valor where jm.id_justificante_masivo is not null and jm.tipo_cobertura in ('dia','vacaciones') "
                            ."union "
                            ."select 3 as orden, jm2.id_justificante_masivo as valor where jm2.id_justificante_masivo is not null and jm2.tipo_cobertura in ('dia','vacaciones') "
                            ."union "
                            ."select 4 as orden, j.id_justificante as valor where j.id_justificante is not null and j.tipo_cobertura in ('dia','vacaciones') "
                            ."union "
                            ."select 5 as orden, jm.id_justificante_masivo as valor where jm.id_justificante_masivo is not null and jm.tipo_cobertura not in ('dia','vacaciones') "
                            ."union "
                            ."select 6 as orden, jm2.id_justificante_masivo as valor where jm2.id_justificante_masivo is not null and jm2.tipo_cobertura not in ('dia','vacaciones') "
                            ."union "
                            ."select 7 as orden, j.id_justificante as valor where j.id_justificante is not null "
                            ."union "
                            ."select 8 as orden, 99 as valor where i.cve_tipo_incidente is not null and di.id_dia_inhabil is null and jm.id_justificante_masivo is null and j.id_justificante is null and date_trunc('minute', i.hora_salida) - date_trunc('minute', i.hora_entrada) >= '8:00' "
                            ."order by orden "
                        .") as cj "
                    ."limit 1 ) as id_justificante "
                ."from "
                    ."incidentes_periodo(fech_ini, fech_fin, tolerancia_retardo, tolerancia_asistencia) i "
                    ."left join dia_inhabil di on di.fecha = i.fecha "
                    ."left join justificante_masivo jm on  "
                        ."i.fecha between jm.fecha and coalesce(jm.fech_fin, jm.fecha)  "
                        ."and jm.id_justificante_masivo not in (select distinct id_justificante_masivo from justificante_masivo_empleado) "
                    ."left join justificante_masivo jm2 on  "
                        ."i.fecha between jm2.fecha and coalesce(jm2.fech_fin, jm2.fecha)  "
                        ."and i.id_empleado in (select jme.id_empleado from justificante_masivo_empleado jme where jme.id_justificante_masivo = jm2.id_justificante_masivo) "
                    ."left join justificante j on  "
                        ."i.fecha between j.fecha and coalesce(j.fech_fin, j.fecha)  "
                        ."and ( "
                                ."(j.tipo_cobertura = 'entrada' and i.cve_tipo_incidente in ('retardo','entrada_tardia','sin_entrada') ) "
                                ."or "
                                ."(j.tipo_cobertura = 'salida' and i.cve_tipo_incidente in ('salida_temprano','sin_salida') ) "
                                ."or "
                                ."(j.tipo_cobertura in ('dia','vacaciones') and i.cve_tipo_incidente = 'inasistencia' ) "
                            .") "
                        ."and j.id_empleado = i.id_empleado "
                ."order by "
                    ."i.fecha "
                ."; "
            ."end; "
            ."$$ language plpgsql strict immutable; "
            ."";
        $query = $this->db->query($sql);
    }

    public function down()
    {
        $sql = "drop function if exists justificacion_periodo(date, date, varchar, varchar) ";
        $query = $this->db->query($sql);
    }
}
